import { Inter } from "next/font/google";
import "./globals.css";
import FooterPage from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ozuna",
  description: "Generated by ozuna",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
